version: '3'

services:
  postgres:
    image: postgres:14
    container_name: container-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: container-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always  # reinicie o container se ele falhar

  adminer:
    image: adminer:latest
    container_name: container-adminer
    restart: always
    ports:
      - 8080:8080

  # publisher:
  #   image: publisher:1.0
  #   container_name: container-publisher
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - "8000:8000"

  # subscriber:
  #   image: subscriber:1.0
  #   container_name: container-subscriber
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #   ports:
  #     - "8010:8010"

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: container-pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres