version: '2.1'
networks:
  asa-bridge:
    ipam:
      config:
        - subnet: 172.19.0.0/16
services:
  projeto_universidade:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      asa-bridge:
        ipv4_address: 172.19.0.20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
